'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Existing = { video: { title: string; slug: string; description: string | null; externalHlsUrl: string | null; status: string } | null; series?: { title: string } | null };
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
export function ContentEditor({ tmdbId, season, episode }: { tmdbId: string; season?: string; episode?: string }) {
  const isEpisode = Boolean(season && episode); const path = isEpisode ? `/admin/content/${tmdbId}/${season}/${episode}` : `/admin/content/${tmdbId}`;
  const [form, setForm] = useState({ title: '', slug: '', description: '', hlsUrl: '', published: false, seriesTitle: '' }); const [state, setState] = useState<'loading' | 'ready' | 'saving' | 'saved' | 'error'>('loading'); const [message, setMessage] = useState(''); const [watchUrl, setWatchUrl] = useState('');
  useEffect(() => { fetch(`/api/v1${path}`, { credentials: 'include' }).then(async (response) => { if (response.status === 401 || response.status === 403) throw new Error('Sign in with an ADMIN account to edit media.'); if (!response.ok) throw new Error('Could not load this media record.'); const data: Existing = await response.json(); const video = data.video; setForm({ title: video?.title ?? '', slug: video?.slug ?? '', description: video?.description ?? '', hlsUrl: video?.externalHlsUrl ?? '', published: video?.status === 'PUBLISHED', seriesTitle: data.series?.title ?? '' }); setState('ready'); }).catch((error: Error) => { setMessage(error.message); setState('error'); }); }, [path]);
  const update = (field: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [field]: value }));
  const loadTmdb = async () => { const type = isEpisode ? 'tv' : 'movie'; setState('saving'); try { const response = await fetch(`/api/v1/admin/tmdb/${type}/${tmdbId}`, { credentials: 'include' }); if (!response.ok) throw new Error(response.status === 503 ? 'TMDb lookup is disabled because TMDB_API_KEY is not configured.' : 'TMDb title was not found.'); const { tmdb } = await response.json(); setForm((current) => ({ ...current, title: tmdb.title ?? current.title, slug: current.slug || slugify(tmdb.title ?? ''), description: tmdb.description ?? current.description, seriesTitle: isEpisode ? tmdb.title ?? current.seriesTitle : current.seriesTitle })); setState('ready'); } catch (error) { setMessage(error instanceof Error ? error.message : 'TMDb lookup failed.'); setState('error'); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setState('saving'); try { const response = await fetch(`/api/v1${path}`, { method: 'PUT', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.message ?? 'Save failed.'); } const body = await response.json(); setWatchUrl(`/watch/${body.videoId}`); setState('saved'); setMessage('Saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Save failed.'); setState('error'); } };
  return <main className="adminShell"><header className="adminHeader"><Link className="brand" href="/">Northstar</Link><span className="muted">Admin / TMDb {tmdbId}{isEpisode ? ` / Season ${season} / Episode ${episode}` : ' / Movie'}</span></header><section className="editor"><div className="editorTitle"><div><span className="eyebrow">Media editor</span><h1>{isEpisode ? `Episode ${episode}` : 'Movie'}</h1></div><button type="button" className="button secondary" disabled={state === 'saving'} onClick={() => void loadTmdb()}>Fill from TMDb</button></div>{state === 'loading' ? <div className="empty">Loading editor...</div> : <form onSubmit={save} className="editorForm">{isEpisode && <label>Series title<input required value={form.seriesTitle} onChange={(event) => update('seriesTitle', event.target.value)} placeholder="Series title" /></label>}<label>Title<input required value={form.title} onChange={(event) => { update('title', event.target.value); if (!form.slug) update('slug', slugify(event.target.value)); }} placeholder="Title" /></label><label>Slug<input required value={form.slug} onChange={(event) => update('slug', slugify(event.target.value))} placeholder="title-slug" /></label><label className="wide">Description<textarea value={form.description} onChange={(event) => update('description', event.target.value)} placeholder="Description" rows={5} /></label><label className="wide">HLS master playlist URL<input required type="url" value={form.hlsUrl} onChange={(event) => update('hlsUrl', event.target.value)} placeholder="https://media.example.com/path/master.m3u8" /></label><label className="toggle"><input type="checkbox" checked={form.published} onChange={(event) => update('published', event.target.checked)} /><span>Publish publicly</span></label><div className="formFooter"><span className={state === 'error' ? 'formError' : 'formState'}>{message}{watchUrl && <> <Link href={watchUrl}>Open published video</Link></>}</span><button className="button" disabled={state === 'saving'}>{state === 'saving' ? 'Saving...' : 'Save media'}</button></div></form>}</section></main>;
}
