import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import rateLimit from '@fastify/rate-limit';
import sensible from '@fastify/sensible';
import { Queue } from 'bullmq';
import { and, desc, eq, like, or, sql } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { db, encodingJobs, seasons, series, videoSources, videos, watchHistory, watchlists, users } from '@streaming/database';
import { B2StorageProvider } from '@streaming/storage';
import { ConfiguredAdProvider } from '@streaming/ads';
import { createSession, deleteSession, getCurrentUser, hashPassword, sessionCookie, verifyPassword } from './auth.js';
import { env } from './config.js';

const app = Fastify({ logger: true });
const queue = new Queue('video.encode', { connection: { url: env.REDIS_URL } });
const storage = new B2StorageProvider({ endpoint: env.B2_ENDPOINT, region: env.B2_REGION, bucket: env.B2_BUCKET, accessKeyId: env.B2_ACCESS_KEY_ID, secretAccessKey: env.B2_SECRET_ACCESS_KEY });
const ads = new ConfiguredAdProvider({ popAdsScriptUrl: env.POPADS_SCRIPT_URL, vastTagUrl: env.VAST_TAG_URL });
const cookieOptions = { httpOnly: true, secure: env.NODE_ENV === 'production', sameSite: 'lax' as const, path: '/', signed: false };

await app.register(cookie);
await app.register(cors, { origin: true, credentials: true });
await app.register(rateLimit, { max: 100, timeWindow: '1 minute' });
await app.register(sensible);
app.setErrorHandler((caught, _request, reply) => { const error = caught as Error & { statusCode?: number }; app.log.error(error); reply.code(error.statusCode ?? 500).send({ error: 'REQUEST_FAILED', message: error.message }); });
app.get('/health', async () => ({ ok: true }));

const requireUser = async (request: typeof app extends never ? never : any) => { const user = await getCurrentUser(request); if (!user) throw app.httpErrors.unauthorized('Authentication required'); return user; };
const requireAdmin = async (request: any) => { const user = await requireUser(request); if (user.role !== 'ADMIN') throw app.httpErrors.forbidden('Admin role required'); return user; };

app.post('/api/v1/auth/register', async (request, reply) => { const body = z.object({ email: z.string().email(), username: z.string().min(3).max(64).regex(/^[a-zA-Z0-9_]+$/), password: z.string().min(12).max(128), displayName: z.string().min(1).max(100) }).parse(request.body); const id = nanoid(); await db.insert(users).values({ id, email: body.email.toLowerCase(), username: body.username, displayName: body.displayName, passwordHash: await hashPassword(body.password), accountStatus: 'ACTIVE' }); const session = await createSession(id); reply.setCookie(sessionCookie, session.token, { ...cookieOptions, expires: session.expiresAt }).code(201).send({ user: { id, email: body.email, username: body.username, displayName: body.displayName, role: 'USER', isPremium: false } }); });
app.post('/api/v1/auth/login', async (request, reply) => { const body = z.object({ email: z.string().email(), password: z.string().min(1) }).parse(request.body); const [user] = await db.select().from(users).where(eq(users.email, body.email.toLowerCase())).limit(1); if (!user || !(await verifyPassword(user.passwordHash, body.password))) throw app.httpErrors.unauthorized('Invalid email or password'); if (user.accountStatus !== 'ACTIVE') throw app.httpErrors.forbidden('Account unavailable'); await db.update(users).set({ lastLoginAt: new Date() }).where(eq(users.id, user.id)); const session = await createSession(user.id); reply.setCookie(sessionCookie, session.token, { ...cookieOptions, expires: session.expiresAt }).send({ user: { id: user.id, email: user.email, username: user.username, displayName: user.displayName, role: user.role, isPremium: false } }); });
app.post('/api/v1/auth/logout', async (request, reply) => { await deleteSession(request.cookies[sessionCookie]); reply.clearCookie(sessionCookie, { path: '/' }).code(204).send(); });
app.get('/api/v1/auth/me', async (request) => ({ user: await getCurrentUser(request) }));

app.get('/api/v1/videos', async (request) => { const query = z.object({ page: z.coerce.number().min(1).default(1), limit: z.coerce.number().min(1).max(50).default(24), q: z.string().max(200).optional() }).parse(request.query); const filter = query.q ? and(eq(videos.status, 'PUBLISHED'), eq(videos.visibility, 'PUBLIC'), or(like(videos.title, `%${query.q}%`), like(videos.description, `%${query.q}%`))) : and(eq(videos.status, 'PUBLISHED'), eq(videos.visibility, 'PUBLIC')); const data = await db.select().from(videos).where(filter).orderBy(desc(videos.createdAt)).limit(query.limit).offset((query.page - 1) * query.limit); return { data, page: query.page }; });
app.get('/api/v1/videos/:id', async (request) => { const { id } = z.object({ id: z.string() }).parse(request.params); const [video] = await db.select().from(videos).where(eq(videos.id, id)).limit(1); if (!video || (video.status !== 'PUBLISHED' && video.visibility !== 'PUBLIC')) throw app.httpErrors.notFound('Video not found'); const user = await getCurrentUser(request); const [history] = user ? await db.select().from(watchHistory).where(and(eq(watchHistory.userId, user.id), eq(watchHistory.videoId, id))).limit(1) : []; const hlsUrl = video.externalHlsUrl ?? (video.hlsMasterKey && env.B2_PUBLIC_BASE_URL ? `${env.B2_PUBLIC_BASE_URL.replace(/\/$/, '')}/${video.hlsMasterKey}` : null); const adConfiguration = await ads.getConfiguration({ videoId: id, isPremium: Boolean(user?.isPremium) }); return { video, hlsUrl, resumePositionSeconds: history?.positionSeconds ?? 0, ads: adConfiguration }; });
app.post('/api/v1/videos', async (request, reply) => { await requireAdmin(request); const body = z.object({ title: z.string().min(1).max(255), slug: z.string().min(1).max(280).regex(/^[a-z0-9-]+$/), description: z.string().max(10000).optional(), contentType: z.enum(['MOVIE', 'EPISODE']).default('MOVIE'), seasonId: z.string().optional(), episodeNumber: z.number().int().positive().optional(), tmdbId: z.number().int().positive().optional() }).refine((value) => value.contentType === 'MOVIE' || (value.seasonId && value.episodeNumber), 'Episodes require seasonId and episodeNumber').parse(request.body); const video = { id: nanoid(), ...body, status: 'DRAFT' as const }; await db.insert(videos).values(video); reply.code(201).send({ video }); });
app.post('/api/v1/videos/:id/external-hls', async (request) => { await requireAdmin(request); const { id } = z.object({ id: z.string() }).parse(request.params); const body = z.object({ url: z.string().url().max(2048).refine((url) => new URL(url).protocol === 'https:' && new URL(url).pathname.toLowerCase().includes('.m3u8'), 'A HTTPS .m3u8 URL is required') }).parse(request.body); await db.update(videos).set({ externalHlsUrl: body.url, hlsMasterKey: null, status: 'READY', encodingProgress: 100, encodingStage: 'external-hls' }).where(eq(videos.id, id)); return { status: 'READY', source: 'external-hls' }; });
app.post('/api/v1/series', async (request, reply) => { await requireAdmin(request); const body = z.object({ title: z.string().min(1).max(255), slug: z.string().regex(/^[a-z0-9-]+$/), description: z.string().max(10000).optional(), tmdbId: z.number().int().positive().optional(), posterPath: z.string().max(512).optional(), backdropPath: z.string().max(512).optional() }).parse(request.body); const record = { id: nanoid(), ...body }; await db.insert(series).values(record); reply.code(201).send({ series: record }); });
app.post('/api/v1/series/:seriesId/seasons', async (request, reply) => { await requireAdmin(request); const { seriesId } = z.object({ seriesId: z.string() }).parse(request.params); const body = z.object({ seasonNumber: z.number().int().min(0), title: z.string().max(255).optional(), tmdbId: z.number().int().positive().optional(), posterPath: z.string().max(512).optional() }).parse(request.body); const record = { id: nanoid(), seriesId, ...body }; await db.insert(seasons).values(record); reply.code(201).send({ season: record }); });
app.get('/api/v1/admin/tmdb/:mediaType/:tmdbId', async (request) => { await requireAdmin(request); if (!env.TMDB_API_KEY) throw app.httpErrors.serviceUnavailable('TMDB_API_KEY is not configured'); const { mediaType, tmdbId } = z.object({ mediaType: z.enum(['movie', 'tv']), tmdbId: z.coerce.number().int().positive() }).parse(request.params); const response = await fetch(`${env.TMDB_BASE_URL}/${mediaType}/${tmdbId}?language=en-US`, { headers: { Authorization: `Bearer ${env.TMDB_API_KEY}`, accept: 'application/json' } }); if (!response.ok) throw app.httpErrors.notFound('TMDb title not found'); const item = await response.json() as { id: number; title?: string; name?: string; overview?: string; poster_path?: string; backdrop_path?: string; release_date?: string; first_air_date?: string; seasons?: unknown[] }; return { tmdb: { id: item.id, title: item.title ?? item.name, description: item.overview, posterPath: item.poster_path, backdropPath: item.backdrop_path, releaseDate: item.release_date ?? item.first_air_date, seasons: item.seasons ?? [] } }; });
app.get('/api/v1/ads/config/:videoId', async (request) => { const { videoId } = z.object({ videoId: z.string() }).parse(request.params); const user = await getCurrentUser(request); return ads.getConfiguration({ videoId, isPremium: Boolean(user?.isPremium) }); });
app.post('/api/v1/videos/:id/upload', async (request) => { await requireAdmin(request); const { id } = z.object({ id: z.string() }).parse(request.params); const body = z.object({ fileName: z.string().min(1).max(255), contentType: z.string().regex(/^video\//), sizeBytes: z.number().int().positive().max(env.MAX_UPLOAD_BYTES) }).parse(request.body); const key = `sources/${id}/${nanoid()}-${body.fileName.replace(/[^a-zA-Z0-9._-]/g, '_')}`; const uploadUrl = await storage.uploadUrl(key, body.contentType); await db.update(videos).set({ status: 'UPLOADING' }).where(eq(videos.id, id)); return { uploadUrl, key, expiresIn: 3600 }; });
app.post('/api/v1/videos/:id/upload/complete', async (request) => { await requireAdmin(request); const { id } = z.object({ id: z.string() }).parse(request.params); const body = z.object({ key: z.string().startsWith(`sources/${id}/`), fileName: z.string(), contentType: z.string().regex(/^video\//), sizeBytes: z.number().int().positive() }).parse(request.body); const metadata = await storage.getObjectMetadata(body.key); if (!metadata.contentLength || metadata.contentLength > env.MAX_UPLOAD_BYTES) throw app.httpErrors.badRequest('Invalid uploaded object'); const sourceId = nanoid(); await db.insert(videoSources).values({ id: sourceId, videoId: id, objectKey: body.key, fileName: body.fileName, contentType: body.contentType, sizeBytes: metadata.contentLength }); await db.update(videos).set({ status: 'QUEUED', encodingProgress: 0, encodingStage: 'queued' }).where(eq(videos.id, id)); const job = await queue.add('video.encode', { videoId: id, sourceKey: body.key }, { attempts: 3, backoff: { type: 'exponential', delay: 30_000 }, removeOnComplete: 100, removeOnFail: 500 }); await db.insert(encodingJobs).values({ id: nanoid(), videoId: id, bullJobId: String(job.id), state: 'QUEUED', stage: 'queued' }); return { jobId: job.id, status: 'QUEUED' }; });
app.get('/api/v1/videos/:id/status', async (request) => { await requireAdmin(request); const { id } = z.object({ id: z.string() }).parse(request.params); const [video] = await db.select({ status: videos.status, progress: videos.encodingProgress, stage: videos.encodingStage, error: videos.encodingError }).from(videos).where(eq(videos.id, id)).limit(1); if (!video) throw app.httpErrors.notFound(); return video; });
app.post('/api/v1/watch-history', async (request) => { const user = await requireUser(request); const body = z.object({ videoId: z.string(), positionSeconds: z.number().int().min(0), durationSeconds: z.number().int().positive(), watchedSeconds: z.number().int().min(0) }).parse(request.body); await db.insert(watchHistory).values({ userId: user.id, ...body, lastWatchedAt: new Date() }).onConflictDoUpdate({ target: [watchHistory.userId, watchHistory.videoId], set: { positionSeconds: body.positionSeconds, durationSeconds: body.durationSeconds, watchedSeconds: sql`${watchHistory.watchedSeconds} + ${body.watchedSeconds}`, lastWatchedAt: new Date() } }); return { ok: true }; });
app.get('/api/v1/watchlist', async (request) => { const user = await requireUser(request); return { data: await db.select({ video: videos }).from(watchlists).innerJoin(videos, eq(watchlists.videoId, videos.id)).where(eq(watchlists.userId, user.id)).orderBy(desc(watchlists.createdAt)) }; });
app.post('/api/v1/watchlist', async (request) => { const user = await requireUser(request); const { videoId } = z.object({ videoId: z.string() }).parse(request.body); await db.insert(watchlists).values({ userId: user.id, videoId }).onConflictDoNothing(); return { ok: true }; });
app.delete('/api/v1/watchlist/:videoId', async (request, reply) => { const user = await requireUser(request); const { videoId } = z.object({ videoId: z.string() }).parse(request.params); await db.delete(watchlists).where(and(eq(watchlists.userId, user.id), eq(watchlists.videoId, videoId))); reply.code(204).send(); });

await app.listen({ port: env.API_PORT, host: '0.0.0.0' });
